### ISSUE TITLE
Question: how to contribute syntax fix & new charts type 

### ISSUE THREAD

**Issue by trongthanh** [monaqa/tree-sitter-mermaid#9]
I'd like to help update some of the new chart type but don't know where to start. There are different grammar* files in the repo and I don't know which one is actually used by nvim-tree-sitter. Any pointers to the documentation or examples on this topic are appreciated.

**Comment by monaqa** [comment]
First of all, thank you for considering contributing.

This repository is generated based on the general tree-sitter parser creation process, and has a mechanism to generate src/parser.c from grammar.js.

For more information, please read https://tree-sitter.github.io/tree-sitter/creating-parsers.

**Comment by trongthanh** [comment]
Please see my PR #10
